Add command to reset a user's password and email it to them
tardisproject/usertools pull request #7
Opened 2021-10-07 17:00 UTC by penalosa

Add a `resetpw` subcommand that resets a user's password and emails it to them

2021-10-07 17:03 UTC, AbstractBeliefs commented
Can we look at if `passwd -e` works correctly on tardis? If so, we should do that to force a new password on the next login.

2021-10-07 17:06 UTC, mayacopeland reviewed
Doesn't this need a -?

2021-10-11 08:25 UTC, qaisjp commented on .gitignore
> +ldap.conf
There should be a new line at the end of files

2021-10-12 07:33 UTC, AbstractBeliefs requested changes
Once the error handling is updated I'm happy to approve this. I've seen it tested as well.

I still don't think emailing cleartext passwords is a good way forward but I can't think of anything else that is pragmatic just now. You need to have someone actively looking at #11 or we're going to end up with lots and lots of active passwords sitting in cleartext in inboxes just waiting to be abused, with no way for us to track or expire them.

2021-10-12 07:33 UTC, AbstractBeliefs commented on tardis/commands/resetpw.py
> +#   100 - User not found
Can we update this to use the error registry that's since landed?

2024-03-06 01:01 UTC, penalosa commented
This is extremely out of date, so I'm going to close this. Feel free to pick it back up if it's useful!

2024-03-06 01:01 UTC, closed without merging